name: docs

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        install_extensions: false
